data <- data %>%
  mutate(
    Metro_Region = sprintf("%02d", as.numeric(Metro_Region)),
    capital_city = case_match(Metro_Region,
                              "01" ~ "Manaus",
                              "02" ~ "Belém",
                              "03" ~ "Belém",          
                              "04" ~ "Fortaleza",      
                              "05" ~ "Fortaleza",
                              "06" ~ "Fortaleza",
                              "07" ~ "Fortaleza",
                              "08" ~ "Natal",
                              "09" ~ "João Pessoa",
                              "10" ~ "João Pessoa",
                              "11" ~ "Recife",
                              "12" ~ "Recife",
                              "13" ~ "Recife",         
                              "14" ~ "Aracaju",
                              "15" ~ "Salvador",
                              "16" ~ "Belo Horizonte",
                              "17" ~ "Belo Horizonte",
                              "18" ~ "Vitória",
                              "19" ~ "Rio de Janeiro",
                              "20" ~ "São Paulo",
                              "21" ~ "São Paulo",
                              "22" ~ "São Paulo",
                              "23" ~ "Curitiba",
                              "24" ~ "Curitiba",
                              "25" ~ "Curitiba",
                              "26" ~ "Florianópolis",
                              "27" ~ "Florianópolis",
                              "28" ~ "Florianópolis",
                              "29" ~ "Florianópolis",
                              "30" ~ "Florianópolis",
                              "31" ~ "Florianópolis",
                              "32" ~ "Florianópolis",
                              "33" ~ "Florianópolis",
                              "34" ~ "Porto Alegre",
                              "35" ~ "Goiânia",        
                              "36" ~ "Goiânia",
                              "37" ~ "Porto Alegre",
                              "38" ~ "Porto Alegre",
                              "39" ~ "Porto Alegre",
                              "40" ~ "Brasília",
                              "41" ~ "Fortaleza",      
                              "42" ~ "Recife",        
                              "00" ~ "N/A",
                              .default = NA_character_
    )
  )
